//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tal_DTC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dogsEntities : DbContext
    {
        public dogsEntities()
            : base("name=dogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DogBarberShop> DogBarberShops { get; set; }
    
        public virtual ObjectResult<ViewAppointments_Result> ViewAppointments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAppointments_Result>("ViewAppointments");
        }
    }
}
